### ISSUE TITLE
Revisions Add on breaks functionality of Admin Plugin

### ISSUE THREAD

**Issue by thorben-sha256** [david-szabo97/grav-plugin-admin-addon-revisions#14]
Grav v1.3.10 - Admin v1.6.7.  Admin Addon Revisions v1.3.1
After i updated  Grav and the Admin Plugin  i'm not able to 

- create a Page 
- view /admin/user-manager/admin
- view /admin/config/system

If i try to do one of the things i get the attached Server Error:
<img width="661" alt="bildschirmfoto 2017-12-08 um 20 17 13" src="https://user-images.githubusercontent.com/2337771/33781969-f7bdfb5a-dc56-11e7-9572-72a9c7664ae6.png">

Log File after attempting to create a Page:

```
[2017-12-08 19:25:58] grav.CRITICAL: mkdir(): No such file or directory - Trace: #0 [internal function]: Whoops\Run->handleError(2, 'mkdir(): No suc...', '/var/www/vhosts...', 46, Array) #1 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/user/plugins/admin-addon-revisions/src/Revisions.php(46): mkdir('/var/www/vhosts...', 504) #2 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/user/plugins/admin-addon-revisions/admin-addon-revisions.php(160): AdminAddonRevisions\Revisions->create() #3 [internal function]: Grav\Plugin\AdminAddonRevisionsPlugin->onPageProcessed(Object(RocketTheme\Toolbox\Event\Event), 'onPageProcessed', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #4 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPageProcessed', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #5 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageProcessed', Object(RocketTheme\Toolbox\Event\Event)) #6 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageProcessed', Object(RocketTheme\Toolbox\Event\Event)) #7 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/system/src/Grav/Common/Grav.php(288): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageProcessed', Object(RocketTheme\Toolbox\Event\Event)) #8 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/system/src/Grav/Common/Page/Pages.php(269): Grav\Common\Grav->fireEvent('onPageProcessed', Object(RocketTheme\Toolbox\Event\Event)) #9 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/user/plugins/admin/classes/admin.php(1395): Grav\Common\Page\Pages->addPage(Object(Grav\Common\Page\Page), '/rgsdffdf') #10 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/user/plugins/admin/classes/admin.php(1353): Grav\Plugin\Admin\Admin->getPage('/rgsdffdf') #11 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/user/plugins/admin-addon-media-rename/admin-addon-media-rename.php(134): Grav\Plugin\Admin\Admin->page(true) #12 [internal function]: Grav\Plugin\AdminAddonMediaRenamePlugin->onTwigExtensions(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #13 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #14 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #15 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #16 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/system/src/Grav/Common/Grav.php(288): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #17 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/system/src/Grav/Common/Processors/PagesProcessor.php(25): Grav\Common\Grav->fireEvent('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #18 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/system/src/Grav/Common/Grav.php(132): Grav\Common\Processors\PagesProcessor->process() #19 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/system/src/Grav/Common/Grav.php(379): Grav\Common\Grav->Grav\Common\{closure}() #20 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #21 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/system/src/Grav/Common/Grav.php(355): call_user_func_array(Object(Closure), Array) #22 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/system/src/Grav/Common/Grav.php(133): Grav\Common\Grav->__call('measureTime', Array) #23 /var/www/vhosts/playground.officealpha.de/httpdocs/siteify/glogner/index.php(52): Grav\Common\Grav->process() #24 {main} [] []
```

**Comment by david-szabo97** [comment]
Hi! This has been fixed in the latest hotfix. Please update to v1.3.2

This has been reported and fixed asap. (see #13)
